### ISSUE TITLE
Another error 

### ISSUE THREAD

**Issue by ATMG** [Muqsit/SkyWars#18]
[Server] Server thread/CRITICAL TypeError: "Return value of muqsit\skywars\Loader::getGameHandler() must be an instance of muqsit\skywars\handler\GameHandler, null returned" (EXCEPTION) in "SkyWars-master/src/muqsit/skywars/Loader" at line 116

**Comment by Muqsit** [comment]
Need more backtrace

**Comment by ATMG** [comment]
`[Server] Server thread/DEBUG #9 /jar/PocketMine-MP.3.0.4.phar(1): require(string phar:///jar/PocketMine-MP.3.0.4.phar/src/pocketmine/PocketMine.php)
08.07 10:18:52 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
08.07 10:18:52 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1708): pocketmine\Server->enablePlugins(integer 1)
08.07 10:18:52 [Server] Server thread/DEBUG #6 src/pocketmine/Server(1914): pocketmine\Server->enablePlugin(muqsit\skywars\Loader object)
08.07 10:18:52 [Server] Server thread/DEBUG #5 src/pocketmine/Server(1928): pocketmine\plugin\PluginManager->enablePlugin(muqsit\skywars\Loader object)
08.07 10:18:52 [Server] Server thread/DEBUG #4 src/pocketmine/plugin/PluginManager(625): pocketmine\plugin\PluginManager->disablePlugin(muqsit\skywars\Loader object)
08.07 10:18:52 [Server] Server thread/DEBUG #3 src/pocketmine/plugin/PluginManager(704): pocketmine\plugin\PluginBase->setEnabled(boolean )
08.07 10:18:52 [Server] Server thread/DEBUG #2 src/pocketmine/plugin/PluginBase(104): muqsit\skywars\Loader->onDisable()
08.07 10:18:52 [Server] Server thread/DEBUG #1 SkyWars_dev-17.phar/src/muqsit/skywars/Loader(131): muqsit\skywars\Loader->saveGames()
08.07 10:18:52 [Server] Server thread/DEBUG #0 SkyWars_dev-17.phar/src/muqsit/skywars/Loader(140): muqsit\skywars\Loader->getGameHandler()
08.07 10:18:52 [Server] Server thread/CRITICAL TypeError: "Return value of muqsit\skywars\Loader::getGameHandler() must be an instance of muqsit\skywars\handler\GameHandler, null returned" (EXCEPTION) in "SkyWars_dev-17.phar/src/muqsit/skywars/Loader" at line 116
 Disabling SkyWars v1.0.0`

**Comment by ATMG** [comment]
I fixed that error, but now I'm getting another one about furnances not having a $namedtag property:
``` [Server] Server thread/DEBUG #13 /jar/PocketMine-MP.3.0.4.phar(1): require(string phar:///jar/PocketMine-MP.3.0.4.phar/src/pocketmine/PocketMine.php)
09.07 20:44:28 [Server] Server thread/DEBUG #12 src/pocketmine/PocketMine(237): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
09.07 20:44:28 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1708): pocketmine\Server->enablePlugins(integer 1)
09.07 20:44:28 [Server] Server thread/DEBUG #10 src/pocketmine/Server(1914): pocketmine\Server->enablePlugin(muqsit\skywars\Loader object)
09.07 20:44:28 [Server] Server thread/DEBUG #9 src/pocketmine/Server(1928): pocketmine\plugin\PluginManager->enablePlugin(muqsit\skywars\Loader object)
09.07 20:44:28 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PluginManager(618): pocketmine\plugin\PluginBase->setEnabled(boolean 1)
09.07 20:44:28 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/PluginBase(102): muqsit\skywars\Loader->onEnable()
09.07 20:44:28 [Server] Server thread/DEBUG #6 SkyWars-master/src/muqsit/skywars/Loader(49): muqsit\skywars\Loader->initGames()
09.07 20:44:28 [Server] Server thread/DEBUG #5 SkyWars-master/src/muqsit/skywars/Loader(70): muqsit\skywars\handler\GameHandler->init(muqsit\skywars\Loader object)
09.07 20:44:28 [Server] Server thread/DEBUG #4 SkyWars-master/src/muqsit/skywars/handler/GameHandler(47): muqsit\skywars\game\SkyWars::fromConfig(array Array())
09.07 20:44:28 [Server] Server thread/DEBUG #3 SkyWars-master/src/muqsit/skywars/game/SkyWars(126): muqsit\skywars\game\SkyWars->__construct(string Steampunk, string Steampunk, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object, pocketmine\math\Vector3 object)
09.07 20:44:28 [Server] Server thread/DEBUG #2 SkyWars-master/src/muqsit/skywars/game/SkyWars(224): muqsit\skywars\game\SkyWars->createChunkBackup()
09.07 20:44:28 [Server] Server thread/DEBUG #1 SkyWars-master/src/muqsit/skywars/game/SkyWars(243): muqsit\skywars\utils\ChunkBackup->store()
09.07 20:44:28 [Server] Server thread/DEBUG #0 SkyWars-master/src/muqsit/skywars/utils/ChunkBackup(64): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined property: pocketmine\tile\Furnace::$namedtag, string /plugins/SkyWars-master/src/muqsit/skywars/utils/ChunkBackup.php, integer 64, array Array())
09.07 20:44:28 [Server] Server thread/CRITICAL ErrorException: "Undefined property: pocketmine\tile\Furnace::$namedtag" (EXCEPTION) in "SkyWars-master/src/muqsit/skywars/utils/ChunkBackup" at line 64```
