### ISSUE TITLE
problem onjoin arena

### ISSUE THREAD

**Issue by SuperKali** [Muqsit/SkyWars#5]
when I enter the game, having set everything up, I turn out to be under the blocks. 
![minecraft 30_05_2018 16_09_41](https://user-images.githubusercontent.com/19473898/40725591-1a992762-6424-11e8-9daa-5de5c66ef99c.png)

**Comment by SuperKali** [comment]
![minecraft 30_05_2018 16_12_17](https://user-images.githubusercontent.com/19473898/40725645-3f6fafca-6424-11e8-8a48-c2eb8080d1d5.png)

**Comment by SuperKali** [comment]
it practically does not teleport you into the arena

**Comment by SuperKali** [comment]
the chests not have any item inside

**Comment by SuperKali** [comment]
[14:18:37] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\entity\EntityDamageEvent' to 'SkyWars v1.0.0': Y coordinate -36 is out of range! on muqsit\skywars\game\SkyWarsListener
[14:18:37] [Server thread/CRITICAL]: InvalidArgumentException: "Y coordinate -36 is out of range!" (EXCEPTION) in "src/pocketmine/level/Level" at line 258

**Comment by SuperKali** [comment]
![minecraft 30_05_2018 16_19_11](https://user-images.githubusercontent.com/19473898/40726046-34ebb872-6425-11e8-9291-713bf777c488.png)
i have won the match but not an teleported on default world

**Comment by Muqsit** [comment]
If you modify blocks of a map/game/arena, make sure you execute `/sw rebackup <game>` so SkyWars saves the world.

**Comment by SuperKali** [comment]
sorry for spam , i tried to restart the server and i see this error:
