### ISSUE TITLE
same problem with last update

### ISSUE THREAD

**Issue by SuperKali** [Muqsit/SkyWars#6]
![minecraft 30_05_2018 16_09_41](https://user-images.githubusercontent.com/19473898/40731700-e7716f1c-6431-11e8-9844-610eb4e2543c.png)

**Comment by SuperKali** [comment]
i spawned inside blocks when i join on the game

**Comment by Muqsit** [comment]
is your game in another level?

**Comment by SuperKali** [comment]
yes

**Comment by SuperKali** [comment]
if you do join on my server i write the ip

**Comment by SuperKali** [comment]
i try now

**Comment by CreativePigGR** [comment]
Your plugin have not blocks plz fix it
