### ISSUE TITLE
player lose remained on arena

### ISSUE THREAD

**Issue by SuperKali** [Muqsit/SkyWars#9]
i won the game but the player that have lose is remained on the arena
![photo_2018-05-30_18-03-48](https://user-images.githubusercontent.com/19473898/40732869-9aa9a426-6434-11e8-8298-e6abc29c33af.jpg)

**Comment by Muqsit** [comment]
Can you send your games.yml

**Comment by SuperKali** [comment]
http://networkgames.eu/OwnCloud/games.yml

**Comment by Muqsit** [comment]
Can you test with the latest commit?

**Comment by SuperKali** [comment]
@Muqsit yes

**Comment by SuperKali** [comment]
@Muqsit now work!
